spring:
  application:
    name: security

  # 실행 시 .env.{profile} 불러오기
  # SPRING_PROFILES_ACTIVE가 없으면 기본값으로 development 사용
  config:
    import: optional:file:.env.${SPRING_PROFILES_ACTIVE:development}[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update      # 개발 단계면 create/update, 운영은 신중하게 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084
  servlet:
    session:
      timeout: 30m   # 30분 (m: 분, s: 초, h: 시간)
      cookie:
        same-site: lax   # 기본은 Lax 권장 (로그인 CSRF 완화)
        secure: false    # HTTPS 환경에서는 true로

frontend:
  url: ${FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600 # 1시간